apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.routes[0].name }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
  hostnames:
  {{- range .Values.routes[0].hostnames }}
  - {{ . | quote }}
  {{- end }}
  rules:
  {{- range .Values.routes[0].rules }}
  - matches:
    - path:
        type: {{ .pathType }}
        value: {{ .path }}
    backendRefs:
    - name: {{ .backendService }}
      port: {{ .backendPort }}
  {{- end }}
