spring:
  application:
    name: api-communication-study
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

app:
  security:
    clients:
      - tenant-id: tenant-alpha
        client-id: web-client
        hashed-api-key: 024f6c9525465fbec0047e2686f02a413c52241fde8af273148c419fa18fb312
  study:
    rate-limit:
      max-requests: 2
      window: 1m
    cache:
      ttl: 45s
