app:
  security:
    clients:
      - tenant-id: tenant-alpha
        client-id: web-client
        hashed-api-key: 024f6c9525465fbec0047e2686f02a413c52241fde8af273148c419fa18fb312
  study:
    rate-limit:
      max-requests: 5
      window: 1m
    cache:
      ttl: 45s

spring:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

logging:
  level:
    org.testcontainers: INFO
    com.github.dockerjava: WARN
    org.hibernate.SQL: DEBUG
    io.github.jongminchung: DEBUG
