version: "3.9"

services:
  log4j2-app-file:
    build:
      context: ./poc/app-file
    privileged: true
    cgroupns: host
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - app-logs:/var/log/log4j2-app

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.3
    user: root
    volumes:
      - app-logs:/var/log/log4j2-app:ro
      - ./poc/configs/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on:
      - log4j2-app-file
      - elasticsearch

  central-sync:
    image: busybox:1.36
    command: >-
      sh -c "mkdir -p /central/log4j2-app; while true; do cp -a /var/log/log4j2-app/. /central/log4j2-app/; sleep 5; done"
    volumes:
      - app-logs:/var/log/log4j2-app:ro
      - central-storage:/central
    depends_on:
      - log4j2-app-file

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

volumes:
  app-logs:
  central-storage:
